"""composeai's dev/test kit: :class:`FakeModel`, cassette record/replay, and
the ``@agent(cache=True)`` response cache.

``FakeModel`` implements the :class:`~composeai.models.base.Model` protocol
with a scripted sequence of responses. No network, no provider SDK: it's
the tool the rest of composeai's test suite (and downstream users') uses to
exercise agent/tool logic without hitting a real model.

The rest of this module closes the loop between that offline world and a
real one:

- :func:`record_cassette` / :func:`replay_cassette` -- context managers that
  intercept :func:`composeai.models.registry.resolve` so every resolved
  model is transparently recorded to (or replayed from) a JSON cassette
  file. The :func:`cassette` pytest fixture picks the right mode
  automatically per test: record when ``COMPOSE_RECORD=1`` is set, replay
  when the cassette file already exists, otherwise pass through live
  (neither recording nor replaying) -- see its own docstring.
- :class:`CachingModel` -- the ``Model`` wrapper behind ``@agent(cache=True)``
  (wired up in :mod:`composeai.agentfn`'s ``_make_slot``): a filesystem-backed
  cache of ``complete()`` responses, keyed by the same request hash cassettes
  use. Streaming bypasses it entirely (documented on the class).

None of this requires a provider SDK: cassette/cache machinery only ever
sees whatever :class:`~composeai.models.base.Model` ``registry.resolve()``
would have returned, real or ``FakeModel``, and never imports
``composeai.models.anthropic``/``composeai.models.openai`` itself.
"""

from __future__ import annotations

import contextvars
import hashlib
import json
import os
import re
from collections.abc import AsyncIterator, Callable, Iterator, Sequence
from contextlib import contextmanager
from dataclasses import replace
from pathlib import Path
from typing import Any

from ._encoding import from_jsonable, register_serializable, to_jsonable
from ._ids import new_ulid
from .errors import ComposeError, ConfigError
from .messages import ContentPart, Message, StopReason, TextPart, ThinkingPart, ToolCallPart, Usage
from .models import registry
from .models.base import Model, ModelRequest, ModelResponse, RawStreamEvent

# `ModelResponse` (a plain dataclass, not a pydantic model) and `StopReason`
# aren't otherwise registered anywhere at import time (unlike `Message` and
# its parts -- see the bottom of composeai.messages) -- a replay-only
# process (one that decodes a cassette entry's `response` without ever
# having *encoded* a ModelResponse itself first) needs them registered
# eagerly, the same reasoning as that module's own eager registration.
register_serializable(ModelResponse)
register_serializable(StopReason)

_WORD_OR_WHITESPACE_RE = re.compile(r"\S+|\s+")

_DEFAULT_USAGE = Usage(input_tokens=10, output_tokens=20, cost_complete=False)

# What a script item can be, before being invoked (if callable):
ScriptItem = str | dict[str, Any] | ModelResponse | Callable[[ModelRequest], Any]


class FakeModel:
    """A scripted :class:`~composeai.models.base.Model` for tests.

    ``script`` items are consumed in order, one per :meth:`complete` call:

    - a ``str`` -> a plain text response, stop reason ``END_TURN``.
    - ``{"tool_calls": [{"name", "arguments", "id": optional}, ...], "text": optional}``
      -> an assistant message with one ``ToolCallPart`` per entry (plus a
      leading ``TextPart`` if ``"text"`` is given), stop reason ``TOOL_USE``.
      A missing ``"id"`` is autogenerated with :func:`~composeai._ids.new_ulid`.
    - ``{"json": {...}}`` -> a structured response: ``parsed`` is set to the
      dict, the message's text is its JSON encoding, stop reason ``END_TURN``.
    - a :class:`~composeai.models.base.ModelResponse` -> returned as-is.
    - a callable -> invoked with the :class:`ModelRequest`; its return value
      is interpreted using the rules above (any of the forms above except
      another callable).

    Every request is recorded in :attr:`requests`. Once ``script`` is
    exhausted, further calls raise :class:`~composeai.errors.ComposeError`.
    """

    def __init__(self, script: list[ScriptItem], *, usage: Usage | None = None) -> None:
        self.script: list[ScriptItem] = list(script)
        self._usage = usage
        self.requests: list[ModelRequest] = []
        self._index = 0

    def complete(self, request: ModelRequest) -> ModelResponse:
        self.requests.append(request)
        if self._index >= len(self.script):
            raise ComposeError(
                f"FakeModel script exhausted after {len(self.requests)} request(s): "
                "no more scripted responses left"
            )
        item = self.script[self._index]
        self._index += 1
        if callable(item):
            item = item(request)
        return self._to_response(item, request)

    def stream(self, request: ModelRequest) -> Iterator[RawStreamEvent]:
        """Derive a :class:`RawStreamEvent` sequence from the script item ``complete()`` would use.

        Delegates to :meth:`complete` (so the script is consumed and
        ``request`` recorded exactly the same way, one item per call), then
        synthesizes the resulting message as deltas -- see
        :func:`_synthesize_stream_events` (also used by :class:`ReplayModel`,
        so a cassette replays streaming calls the same word-level way).
        """
        response = self.complete(request)
        yield from _synthesize_stream_events(response)

    async def acomplete(self, request: ModelRequest) -> ModelResponse:
        """Async twin: same script, same order (in-memory, nothing blocks)."""
        return self.complete(request)

    async def astream(self, request: ModelRequest) -> AsyncIterator[RawStreamEvent]:
        """Async twin of stream(): consume one script item, synthesize deltas."""
        response = self.complete(request)
        for event in _synthesize_stream_events(response):
            yield event

    def _to_response(self, item: Any, request: ModelRequest) -> ModelResponse:
        if isinstance(item, ModelResponse):
            return item

        usage = self._usage if self._usage is not None else _DEFAULT_USAGE

        if isinstance(item, str):
            return ModelResponse(
                message=Message.assistant(item),
                stop_reason=StopReason.END_TURN,
                raw_stop_reason="end_turn",
                usage=usage,
                model_id=request.model,
            )

        if isinstance(item, dict):
            if "tool_calls" in item:
                parts: list[ContentPart] = []
                text = item.get("text")
                if text:
                    parts.append(TextPart(text=text))
                for call in item["tool_calls"]:
                    parts.append(
                        ToolCallPart(
                            id=call.get("id") or new_ulid(),
                            name=call["name"],
                            arguments=call.get("arguments", {}),
                        )
                    )
                return ModelResponse(
                    message=Message(role="assistant", parts=parts),
                    stop_reason=StopReason.TOOL_USE,
                    raw_stop_reason="tool_use",
                    usage=usage,
                    model_id=request.model,
                )
            if "json" in item:
                payload = item["json"]
                return ModelResponse(
                    message=Message.assistant(json.dumps(payload)),
                    stop_reason=StopReason.END_TURN,
                    raw_stop_reason="end_turn",
                    usage=usage,
                    model_id=request.model,
                    parsed=payload,
                )
            raise ComposeError(f"FakeModel: unrecognized script item {item!r}")

        raise ComposeError(f"FakeModel: unrecognized script item {item!r}")


def _synthesize_stream_events(response: ModelResponse) -> Iterator[RawStreamEvent]:
    """Turn an already-complete :class:`ModelResponse` into a delta sequence.

    Text and thinking content are each split into word/whitespace-preserving
    chunks (``text_delta``/``thinking_delta`` respectively), each tool call
    becomes started/one args_delta (full JSON)/finished, and the last event
    is always ``response_done`` carrying ``response`` itself unchanged --
    consuming only that one event is exactly equivalent to having called
    ``complete()``. Shared by :meth:`FakeModel.stream` and
    :meth:`ReplayModel.stream` so both synthesize streaming the same way.
    """
    for part in response.message.parts:
        if isinstance(part, TextPart):
            for chunk in _WORD_OR_WHITESPACE_RE.findall(part.text):
                yield RawStreamEvent(kind="text_delta", text=chunk)
        elif isinstance(part, ThinkingPart):
            for chunk in _WORD_OR_WHITESPACE_RE.findall(part.text):
                yield RawStreamEvent(kind="thinking_delta", text=chunk)
        elif isinstance(part, ToolCallPart):
            yield RawStreamEvent(
                kind="tool_call_started", tool_call_id=part.id, tool_name=part.name
            )
            yield RawStreamEvent(
                kind="tool_args_delta",
                text=json.dumps(part.arguments),
                tool_call_id=part.id,
                tool_name=part.name,
            )
            yield RawStreamEvent(
                kind="tool_call_finished", tool_call_id=part.id, tool_name=part.name
            )
    yield RawStreamEvent(kind="response_done", response=response)


# --- cassette hashing --------------------------------------------------------
#
# Two hashes per request, both sha256 hex digests of canonical
# (``sort_keys``, no whitespace) JSON:
#
# - ``full_hash`` covers everything that can change a model's answer *or*
#   how its response must be interpreted: provider label, model id, system
#   prompt, messages, every tool's full spec (name, description,
#   input_schema, strict, requires_approval -- not just names: two agents
#   sharing a tool *name* with different schemas, or different
#   requires_approval gating, must never share a cache/cassette entry),
#   output schema, max_tokens, temperature.
# - ``message_hash`` covers only ``(system, messages)`` -- the part that
#   survives even when a cassette was built from a persisted trace span
#   (see ``compose export``, in ``composeai.cli``), which never recorded
#   provider/tools/output_schema/max_tokens/temperature in the first place.
#   Replay falls back to this when no ``full_hash`` matches (see
#   :class:`ReplayModel`) -- deliberately coarser than ``full_hash``, so a
#   collision across providers/tool-schemas is possible on this fallback
#   path specifically; it exists only for the export/replay use case, which
#   has no finer-grained data to hash in the first place.


def _canonical_json(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _messages_payload(messages: Sequence[Message]) -> list[dict[str, Any]]:
    return [m.model_dump(mode="json") for m in messages]


def compute_message_hash(system: str | None, messages: Sequence[Message]) -> str:
    """sha256 of canonical JSON of ``(system, messages)`` only.

    The one piece every cassette entry can always be matched on, even one
    built by ``compose export`` from a persisted trace (no tools/schema/
    max_tokens/temperature available there -- see :func:`compute_full_hash`).
    """
    payload = {"system": system, "messages": _messages_payload(messages)}
    return _sha256_text(_canonical_json(payload))


def compute_full_hash(request: ModelRequest) -> str:
    """sha256 of canonical JSON of every field that can change a model's answer.

    ``(provider, model, system, messages, tools, output_schema, max_tokens,
    temperature)``. ``provider`` is included so two agents pointed at
    different providers that happen to share a bare model-id string (e.g.
    ``"anthropic/claude-3-5-sonnet"`` vs a self-hosted
    ``"openai-compatible/claude-3-5-sonnet"`` proxy) never share a cache/
    cassette entry -- ``request.model`` alone is the *bare* id, with the
    provider prefix already stripped (see :class:`~composeai.models.base.ModelRequest`).
    ``tools`` hashes each tool's *full* spec (name, description,
    input_schema, strict, requires_approval), sorted by name -- not just
    names: two agents that each define a same-named tool with a different
    schema or a different ``requires_approval`` gate must never be able to
    poison each other's cached/replayed tool-call arguments.
    """
    payload = {
        "provider": request.provider,
        "model": request.model,
        "system": request.system,
        "messages": _messages_payload(request.messages),
        "tools": (
            [
                {
                    "name": t.name,
                    "description": t.description,
                    "input_schema": t.input_schema,
                    "strict": t.strict,
                    "requires_approval": t.requires_approval,
                }
                for t in sorted(request.tools, key=lambda t: t.name)
            ]
            if request.tools
            else None
        ),
        "output_schema": request.output_schema,
        "max_tokens": request.max_tokens,
        "temperature": request.temperature,
    }
    return _sha256_text(_canonical_json(payload))


def _cassette_entry(request: ModelRequest, response: ModelResponse) -> dict[str, Any]:
    return {
        "full_hash": compute_full_hash(request),
        "message_hash": compute_message_hash(request.system, request.messages),
        "request": {
            "model": request.model,
            "system": request.system,
            "messages": _messages_payload(request.messages),
        },
        "response": to_jsonable(response),
    }


# --- RecordingModel / record_cassette ----------------------------------------


class RecordingModel:
    """Proxies a real :class:`~composeai.models.base.Model`, recording every call.

    Constructed by :func:`record_cassette` around whatever
    ``registry.resolve()`` would otherwise have returned -- every
    :meth:`complete` call passes through to the real model and appends one
    cassette entry; a :meth:`stream` call (only exposed when the inner
    model has one -- see below) passes every delta through unchanged and
    records just the final ``response_done`` response, same as one
    ``complete()`` call would have.
    """

    def __init__(self, inner: Model, entries: list[dict[str, Any]]) -> None:
        self._inner = inner
        self._entries = entries
        # Only expose `.stream` when the inner model does -- `_ainvoke_model`
        # (composeai.agentfn) detects streaming support with
        # `getattr(model, "stream", None)`, so this instance must not appear
        # to support it when the model it wraps doesn't.
        inner_stream = getattr(inner, "stream", None)
        if inner_stream is not None:
            self.stream = self._make_stream(inner_stream)

    def complete(self, request: ModelRequest) -> ModelResponse:
        response = self._inner.complete(request)
        self._entries.append(_cassette_entry(request, response))
        return response

    def _make_stream(
        self, inner_stream: Callable[[ModelRequest], Iterator[RawStreamEvent]]
    ) -> Callable[[ModelRequest], Iterator[RawStreamEvent]]:
        def _stream(request: ModelRequest) -> Iterator[RawStreamEvent]:
            for event in inner_stream(request):
                if event.kind == "response_done":
                    assert event.response is not None
                    self._entries.append(_cassette_entry(request, event.response))
                yield event

        return _stream


# Cassette file format version. Bumped 1 -> 2 when `full_hash` started
# covering `provider` and each tool's full spec (description/input_schema/
# strict/requires_approval), not just its name -- a v1 file's `full_hash`
# values were computed with the old, narrower hash material and can never
# match a v2 `compute_full_hash()` call, so replaying one under the new
# code would either spuriously fall back to `message_hash` (silently
# losing the provider/tool-schema disambiguation the bump exists for) or,
# worse, look like a plausible match it isn't. Refusing v1 files outright
# (see :func:`replay_cassette`) is louder and safer than either.
_CASSETTE_VERSION = 2


def _check_not_nested_cassette() -> None:
    if getattr(registry.resolve, "_compose_cassette_active", False):
        raise ConfigError(
            "record_cassette()/replay_cassette() cannot be nested -- "
            "registry.resolve() is already intercepted by another active "
            "cassette context. Nesting isn't supported: a plain save/restore "
            "of registry.resolve means whichever context exits last would "
            "clobber the other's interception. Close the outer cassette "
            "context first, or record/replay everything through one shared "
            "context instead."
        )


@contextmanager
def record_cassette(path: str | Path) -> Iterator[None]:
    """Record every model resolved (via ``registry.resolve()``) during the block to ``path``.

    Intercepts :func:`composeai.models.registry.resolve` for the duration
    of the ``with`` block so every resolved model -- a real provider
    adapter, ``FakeModel``, anything ``resolve()`` would otherwise return --
    is wrapped in a :class:`RecordingModel`. On exit, writes ``path`` as
    ``{"version": 2, "entries": [...]}`` (creating parent directories as
    needed), one entry per :meth:`~RecordingModel.complete` call (a
    ``stream()`` call adds one entry too, for its final response).

    Restores the original ``registry.resolve`` on exit even if the block
    raised, but the cassette file is still written in that case (whatever
    was recorded before the failure is worth keeping).

    Raises :class:`~composeai.errors.ConfigError` immediately (before
    touching ``registry.resolve`` or ``path``) if called while another
    ``record_cassette``/``replay_cassette`` context is already active --
    nesting isn't supported (see :func:`_check_not_nested_cassette`).

    Recording writes the full, unredacted request (system prompt, every
    message) and response to ``path`` regardless of
    ``COMPOSE_TRACE_CONTENT`` -- that flag only governs what a *trace span*
    captures; a cassette must store full content to be replayable at all.
    See the "Rules of the road" section of the README.
    """
    _check_not_nested_cassette()
    path = Path(path)
    entries: list[dict[str, Any]] = []
    original_resolve = registry.resolve

    def _wrapped_resolve(model: str | Model) -> Model:
        real = original_resolve(model)
        return RecordingModel(real, entries)

    _wrapped_resolve._compose_cassette_active = True  # type: ignore[attr-defined]

    registry.resolve = _wrapped_resolve  # type: ignore[assignment]
    try:
        yield
    finally:
        registry.resolve = original_resolve  # type: ignore[assignment]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({"version": _CASSETTE_VERSION, "entries": entries}, indent=2))


# --- ReplayModel / replay_cassette -------------------------------------------


class ReplayModel:
    """Answers :meth:`complete`/:meth:`stream` from a fixed list of cassette entries.

    Matches by ``full_hash`` first, falling back to ``message_hash`` when
    no (still-available) entry's ``full_hash`` matches -- this is what lets
    a cassette built by ``compose export`` (which only ever has a
    ``message_hash``, no tools/schema recorded) replay successfully.
    Entries are consumed in order *within whichever hash matched*: the
    same request made twice against a cassette with two matching entries
    gets the first, then the second (an ``_available`` flag per entry,
    scanned front-to-back, rather than removing from a list, so `full_hash`
    and `message_hash` lookups over the same entries can never disagree
    about what's already been consumed).

    :meth:`stream` synthesizes word-level deltas from whatever
    :meth:`complete` would have returned (see
    :func:`_synthesize_stream_events`) -- a cassette never stores raw
    stream deltas, only the final response.
    """

    def __init__(self, entries: list[dict[str, Any]]) -> None:
        self._entries = list(entries)
        self._available = [True] * len(self._entries)

    def complete(self, request: ModelRequest) -> ModelResponse:
        index = self._find(request)
        self._available[index] = False
        return from_jsonable(self._entries[index]["response"])

    def stream(self, request: ModelRequest) -> Iterator[RawStreamEvent]:
        response = self.complete(request)
        yield from _synthesize_stream_events(response)

    def _find(self, request: ModelRequest) -> int:
        full = compute_full_hash(request)
        for i, entry in enumerate(self._entries):
            if self._available[i] and entry.get("full_hash") == full:
                return i
        message = compute_message_hash(request.system, request.messages)
        for i, entry in enumerate(self._entries):
            if self._available[i] and entry.get("message_hash") == message:
                return i
        raise ComposeError(
            f"no cassette entry matches this request (model={request.model!r}, "
            f"full_hash={full!r}, message_hash={message!r}) -- re-record the "
            "cassette (e.g. COMPOSE_RECORD=1) if the request legitimately changed"
        )


@contextmanager
def replay_cassette(path: str | Path) -> Iterator[None]:
    """Replay ``path`` for every model resolved (via ``registry.resolve()``) during the block.

    Intercepts :func:`composeai.models.registry.resolve` so it returns one
    shared :class:`ReplayModel` (built from ``path``'s entries) for every
    call, *without ever calling the real* ``resolve()`` -- no provider
    adapter (or its SDK) is constructed during replay, regardless of which
    ``"provider/model-id"`` string (or ``Model`` instance) was asked for.

    Raises :class:`~composeai.errors.ConfigError` if ``path``'s
    ``"version"`` isn't :data:`_CASSETTE_VERSION` (a v1 file predates
    ``full_hash`` covering ``provider``/full tool specs -- see
    :data:`_CASSETTE_VERSION`'s comment -- so it can never produce a
    meaningful ``full_hash`` match under the current code) or if called
    while another cassette context is already active (nesting isn't
    supported; see :func:`_check_not_nested_cassette`).
    """
    _check_not_nested_cassette()
    path = Path(path)
    data = json.loads(path.read_text())
    file_version = data.get("version")
    if file_version != _CASSETTE_VERSION:
        raise ConfigError(
            f"cassette {path} is version {file_version!r}, expected "
            f"{_CASSETTE_VERSION} -- re-record it (e.g. `COMPOSE_RECORD=1` "
            "against the real provider, or `compose export` again from a "
            "persisted run) to pick up the current hash format"
        )
    replay_model = ReplayModel(data.get("entries", []))
    original_resolve = registry.resolve

    def _wrapped_resolve(model: str | Model) -> Model:
        return replay_model

    _wrapped_resolve._compose_cassette_active = True  # type: ignore[attr-defined]

    registry.resolve = _wrapped_resolve  # type: ignore[assignment]
    try:
        yield
    finally:
        registry.resolve = original_resolve  # type: ignore[assignment]


# --- cassette pytest fixture --------------------------------------------------

try:
    import pytest as _pytest
except ImportError:  # pragma: no cover -- pytest is a dev dependency, not a runtime one
    _pytest = None

if _pytest is not None:

    @_pytest.fixture
    def cassette() -> Callable[[str | Path], Any]:
        """pytest fixture: ``with cassette(path): ...`` records, replays, or passes through live.

        - ``COMPOSE_RECORD=1`` set -> :func:`record_cassette` (always
          re-records, even if ``path`` already exists).
        - Else, ``path`` already exists -> :func:`replay_cassette`.
        - Else -> live passthrough: neither wraps nor intercepts anything: a
          real model runs exactly as it would with no cassette involved at
          all, and no file is written.

        Usage::

            def test_x(cassette):
                with cassette("tests/cassettes/x.json"):
                    ...  # exercise an @agent (or anything using registry.resolve())

        Record a fresh cassette with ``COMPOSE_RECORD=1 pytest tests/test_x.py``,
        then commit the resulting file -- subsequent runs replay it offline.
        """

        @contextmanager
        def _use(path: str | Path) -> Iterator[None]:
            p = Path(path)
            if os.environ.get("COMPOSE_RECORD") == "1":
                with record_cassette(p):
                    yield
            elif p.exists():
                with replay_cassette(p):
                    yield
            else:
                yield

        return _use

else:
    cassette = None  # type: ignore[assignment]


# --- CachingModel: the `@agent(cache=True)` response cache -------------------


def _default_cache_dir() -> Path:
    base = os.environ.get("COMPOSE_DIR") or "./.compose"
    return Path(base) / "cache"


class CachingModel:
    """Wraps a :class:`~composeai.models.base.Model` with a filesystem-backed response cache.

    The ``Model`` behind ``@agent(cache=True)`` (see
    ``composeai.agentfn._make_slot``): each :meth:`complete` call is keyed
    by :func:`compute_full_hash`, stored as
    ``{cache_dir}/<key>.json`` (``cache_dir`` defaults to
    ``{COMPOSE_DIR or ./.compose}/cache``, resolved once at construction --
    ``_make_slot`` builds a fresh slot per run, so this still picks up a
    ``COMPOSE_DIR`` change between runs/tests). A hit decodes the stored
    response but returns it with ``usage=Usage()`` (zeroed) -- a cache hit
    must never re-report the tokens it originally cost, since no new call
    was made. ``composeai.agentfn._acall_llm`` reads :attr:`last_was_hit`
    (a duck-typed ``getattr(model, "last_was_hit", False)`` check, right
    after invoking the model) to tag the llm span's
    ``attributes["cached"] = True`` on a hit.

    Applies to :meth:`complete`/:meth:`acomplete` only -- when the inner
    model also supports ``stream()``/``astream()``, this exposes them
    *unwrapped* (straight passthrough, same trick :class:`RecordingModel`
    uses to conditionally expose ``.stream``): a cache would need to store
    and replay deltas too, which isn't implemented, so streaming calls
    always run for real and are never cached, by design. ``acomplete`` and
    ``astream`` are each only exposed when the inner model has the matching
    method -- set to ``None`` in :meth:`__init__` otherwise, which defeats
    the engine's ``getattr(model, "acomplete", None)`` discovery
    (``composeai.models.base``) so it falls back to running this model's
    sync ``complete``/``stream`` off-thread, exactly mirroring the
    provider-adapter shadow-off pattern (e.g. ``AnthropicModel.__init__``
    when constructed with a sync-only injected client).

    Safe for concurrent :meth:`complete`/:meth:`acomplete` calls on the
    *same* instance from multiple threads AND/OR multiple asyncio tasks on
    one thread -- :attr:`last_was_hit` is backed by a
    ``contextvars.ContextVar`` (one per ``CachingModel`` instance), so each
    thread *and* each task observes only the outcome of its own most recent
    call, never another thread's or task's hit/miss racing in between the
    call and the read. A plain ``threading.local`` would isolate by OS
    thread only -- insufficient once ``acomplete`` lets multiple coroutines
    share one instance on a single event-loop thread, which is exactly the
    bug class ``ContextVar`` (task- and thread-isolated) closes. This
    matters because a single agent's model slot (and thus its
    ``CachingModel``) is shared across a ``pipe.map``/``aggregate``
    fan-out's worker threads, or across concurrent ``asyncio.gather``'d
    coroutines under the async engine.

    Writes the full, unredacted response to disk regardless of
    ``COMPOSE_TRACE_CONTENT`` -- that flag only governs what a *trace span*
    captures; the cache must store the real response to be replayable at
    all. See the "Rules of the road" section of the README. Each cache
    file is written atomically (temp file + ``os.replace``) so a process
    killed mid-write, or two threads racing the same key across separate
    ``CachingModel`` instances, can never leave a truncated/corrupt cache
    file behind for a later hit to choke on.
    """

    def __init__(self, inner: Model, cache_dir: str | Path | None = None) -> None:
        self._inner = inner
        self._cache_dir = Path(cache_dir) if cache_dir is not None else _default_cache_dir()
        # One ContextVar per instance (not a module-level singleton) --
        # `last_was_hit` must be reachable from every CachingModel without
        # instances stepping on each other's flag.
        self._hit_flag: contextvars.ContextVar[bool] = contextvars.ContextVar(
            f"CachingModel._hit_flag[{id(self)}]", default=False
        )
        inner_stream = getattr(inner, "stream", None)
        if inner_stream is not None:
            self.stream = inner_stream
        if getattr(inner, "acomplete", None) is None:
            # Discovery-defeat: the inner model has no async complete, so
            # this instance must not appear to either -- the engine falls
            # back to running this model's sync `complete()` off-thread.
            self.acomplete = None  # type: ignore[assignment]
        if getattr(inner, "astream", None) is None:
            self.astream = None  # type: ignore[assignment]

    @property
    def last_was_hit(self) -> bool:
        """Whether THIS THREAD/TASK's most recent complete/acomplete call was a cache hit.

        Backed by a ``contextvars.ContextVar``: parallel map/aggregate
        threads, or concurrent asyncio tasks, sharing one ``CachingModel``
        instance each observe their own flag (a plain instance attribute --
        or a ``threading.local``, once coroutines share one thread -- let
        one caller's hit/miss overwrite another's between the call and the
        read).
        """
        return self._hit_flag.get()

    def complete(self, request: ModelRequest) -> ModelResponse:
        key = compute_full_hash(request)
        path = self._cache_dir / f"{key}.json"
        if path.exists():
            self._hit_flag.set(True)
            cached = from_jsonable(json.loads(path.read_text()))
            return replace(cached, usage=Usage())
        self._hit_flag.set(False)
        response = self._inner.complete(request)
        self._write_cache_file(key, response)
        return response

    async def acomplete(self, request: ModelRequest) -> ModelResponse:
        """Async twin of :meth:`complete`: same cache, same hit/miss semantics.

        Shadowed off (set to ``None`` in :meth:`__init__`) when the inner
        model has no ``acomplete`` -- see the class docstring.

        The cache file I/O itself (``path.exists()``/``path.read_text()`` on
        a hit, :meth:`_write_cache_file` on a miss) runs synchronously on
        the CALLER's own loop -- unlike the rest of the async engine, which
        routes blocking work off-loop (e.g. ``composeai._storeasync``'s
        writer thread). Fine for a testing-only tool exercised by tests, but
        not something to reach for in a latency-sensitive production loop.
        """
        key = compute_full_hash(request)
        path = self._cache_dir / f"{key}.json"
        if path.exists():
            self._hit_flag.set(True)
            cached = from_jsonable(json.loads(path.read_text()))
            return replace(cached, usage=Usage())
        self._hit_flag.set(False)
        # `acomplete` isn't part of the `Model` Protocol (duck-discovered,
        # like the engine itself does -- see `agentfn._ainvoke_model`), so
        # it's reached via `getattr` rather than direct attribute access;
        # `__init__` already guarantees it's present whenever this method
        # itself is (shadowed off to `None` otherwise).
        acomplete_fn = getattr(self._inner, "acomplete")  # noqa: B009
        response = await acomplete_fn(request)
        self._write_cache_file(key, response)
        return response

    async def astream(self, request: ModelRequest) -> AsyncIterator[RawStreamEvent]:
        """Passthrough to the inner model's ``astream`` -- never cached.

        Same reasoning as the (sync) ``stream`` passthrough: a cache would
        need to store and replay deltas, which isn't implemented here.
        Shadowed off (set to ``None`` in :meth:`__init__`) when the inner
        model has no ``astream``.
        """
        astream_fn = getattr(self._inner, "astream")  # noqa: B009
        async for event in astream_fn(request):
            yield event

    def _write_cache_file(self, key: str, response: ModelResponse) -> None:
        self._cache_dir.mkdir(parents=True, exist_ok=True)
        # Atomic write: a plain `write_text` on `path` directly would leave
        # a truncated/corrupt file behind (permanently breaking that cache
        # key for every future hit) if the process died mid-write, or if
        # two threads/processes raced to fill the same key at once. Writing
        # to a private tmp path first and `os.replace`-ing it into place
        # means every observer only ever sees either the old state (no
        # file) or the fully-written new one -- never a partial file.
        path = self._cache_dir / f"{key}.json"
        tmp_path = self._cache_dir / f"{key}.{new_ulid()}.tmp"
        tmp_path.write_text(json.dumps(to_jsonable(response)))
        os.replace(tmp_path, path)


def reset_registries() -> None:
    """Clear the global ``@agent``/``@flow``/``@task`` name registries.

    For test fixtures and REPL/notebook redefinition -- the supported
    replacement for reaching into ``composeai.agentfn._AGENT_REGISTRY`` /
    ``composeai.flow._FLOW_REGISTRY``/``_TASK_REGISTRY`` by hand. After a
    reset, ``resume()`` cannot route a run back to a definition until its
    module re-registers it (re-import or re-decoration).
    """
    from .agentfn import _AGENT_REGISTRY
    from .flow import _FLOW_REGISTRY, _TASK_REGISTRY

    _AGENT_REGISTRY.clear()
    _FLOW_REGISTRY.clear()
    _TASK_REGISTRY.clear()


__all__ = [
    "CachingModel",
    "FakeModel",
    "ReplayModel",
    "RecordingModel",
    "cassette",
    "compute_full_hash",
    "compute_message_hash",
    "record_cassette",
    "replay_cassette",
    "reset_registries",
]
